name = "SpacecraftCA"
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GaussianFilters = "08d575fb-911d-541e-8431-6cfa767e7851"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SatelliteDynamics = "0e7c1a32-1b9f-5532-88a4-e668712d6a4c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"
Dates = "1"
Distributions = "0.25"
HCubature = "1"
POMDPs = "0.9, 1"
POMDPTools = "0.1, 1"
SatelliteDynamics = "0.5"
StaticArrays = "1"
